"use client"
import Head from 'next/head'
import { BiUserPlus } from "react-icons/bi";

import { useState } from 'react';
import CustomTable from './components/table';
import Form from './components/form';



export default function Home() {

  const [visible, setVisible] = useState(false)

  const handler = () => {
    setVisible(!visible)
  }
  return (
    <section>
      <Head>
        <title>CRUD Application</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='py-5'>
        <h1 className='text-xl md:text-5xl text-center font-bold py-10' style={{textAlign: 'center',marginTop: '10px'}}>Employee Management</h1>

        <div className="container mx-auto flex justify-between py-5 border-b">
            <div className="left flex gap-3">
                <button onClick={handler} className='btn btn-primary'>
                  Add Employee <span className='px-1'><BiUserPlus size={23}></BiUserPlus></span>
                </button>
            </div>
        </div>

        {/* collapsable form */}
         { visible ? <Form/> : <></>}
      </main>
     

        {/* table */}
        <div className="container mx-auto">
        <CustomTable />
        </div>

    </section>
  )
}
